"use client";
import { useEffect, useRef, useState } from 'react';
import { flushSync } from 'react-dom';
import { ArrowDownToLine, ArrowLeft, ArrowRight, BedDouble, Bath, Maximize2, Minus, Plus, X, House, MapPin, List, ArrowUpRight, RotateCcw, Compass } from 'lucide-react';
import City from './city';
import './city.css';
import homes from './homes.json';
export type Home = typeof homes[number];
const filters=['All homes','Studios','1–2 beds','3+ beds'];
const stats=(h:Home)=>`${h.beds===0?'Studio':h.beds+' beds'} · ${h.sqft?h.sqft.toLocaleString()+' sq ft':'Area not listed'}`;
export default function CityExplorer(){
 const [filter,setFilter]=useState(0),[hover,setHover]=useState<string|null>(null),[selected,setSelected]=useState<Home|null>(null),[list,setList]=useState(false),[mapZoom,setMapZoom]=useState(1),[reset,setReset]=useState(0),[page,setPage]=useState(0),[zoom,setZoom]=useState(1),[ready,setReady]=useState(false);
 const hoverTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 function changeHover(id:string|null){if(hoverTimer.current)clearTimeout(hoverTimer.current);if(id)setHover(id);else hoverTimer.current=setTimeout(()=>{if(!document.querySelector('.home-pin:hover,.hover-preview:hover'))setHover(null);},700);}
 useEffect(()=>()=>{if(hoverTimer.current)clearTimeout(hoverTimer.current);},[]);
 const closeRef=useRef<HTMLButtonElement>(null),lastFocus=useRef<HTMLElement|null>(null);
 const visible=homes.filter(h=>filter===0||filter===1&&h.beds===0||filter===2&&h.beds>0&&h.beds<3||filter===3&&h.beds>=3);
 const active=homes.find(h=>h.id===hover);
 function open(h:Home){if(hoverTimer.current)clearTimeout(hoverTimer.current);if(!selected)lastFocus.current=document.activeElement as HTMLElement;setSelected(h);setPage(0);setZoom(1);setHover(null);}
 function choose(h:Home){open(h);}
 function close(){setSelected(null);lastFocus.current?.focus();}
 useEffect(()=>{
  type ModelContext={registerTool:(tool:{name:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown},options:{signal:AbortSignal})=>void|Promise<void>};
  const context=(document as Document&{modelContext?:ModelContext}).modelContext;if(!context)return;
  const controller=new AbortController();
  const tools=[{name:'list_homes',description:'List the available San Francisco homes and their floor-plan details.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>homes.map(({id,name,beds,baths,sqft,area})=>({id,name,beds,baths,sqft,area}))},{name:'open_home',description:'Open a home in the visible floor-plan viewer.',inputSchema:{type:'object',properties:{id:{type:'string'}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const id=(input as {id?:string})?.id;const home=homes.find(h=>h.id===id);if(!home)throw new Error('Unknown home ID');flushSync(()=>open(home));return{id:home.id,name:home.name,status:'opened'};}}];
  for(const tool of tools){try{Promise.resolve(context.registerTool(tool,{signal:controller.signal})).catch(()=>{});}catch{}}
  return()=>controller.abort();
 },[]);
 useEffect(()=>{if(!selected)return;closeRef.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')close();if(e.key==='Tab'){const nodes=Array.from(document.querySelectorAll<HTMLElement>('.viewer button:not(:disabled),.viewer a'));const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[selected]);
 return <main className="city-explorer">
  <header className="topbar"><a href="/" className="brand"><span><House size={22}/></span>homebuddy<span className="brand-dot">.</span></a><nav className="city-navigation" aria-label="Homebuddy"><span className="top-location"><MapPin size={15}/> San Francisco, CA</span><a href="/catalog">Furniture library <ArrowUpRight size={15}/></a></nav><button aria-label={list?'Close list':'Browse homes'} className={'browse-button '+(list?'on':'')} onClick={()=>setList(!list)}><List size={17}/><span>{list?'Close list':'Browse homes'}</span><b>{homes.length}</b></button></header>
  <div className="city-heading"><div className="eyebrow"><span/> A PLACE TO CALL HOME</div><h1>San Francisco<span>.</span></h1><p>Choose a floor plan. Explore it. Make it yours.</p><div className="filters" role="group" aria-label="Bedrooms">{filters.map((f,i)=><button key={f} aria-pressed={filter===i} onClick={()=>{setFilter(i);setHover(null);}}>{f}</button>)}</div><div className="home-count"><span className="tiny-pin"/>{visible.length} homes with floor plans</div></div>
  <City homes={visible} hover={hover} onHover={changeHover} onSelect={choose} zoom={mapZoom} reset={reset} onReady={()=>setReady(true)}/>
  {!ready&&<div className="map-loading"><House size={25}/><span>Bringing the city into view</span></div>}
  <div className="map-controls"><button title="Zoom in" aria-label="Zoom map in" onClick={()=>setMapZoom(v=>Math.min(1.7,v+.15))}><Plus/></button><button title="Zoom out" aria-label="Zoom map out" onClick={()=>setMapZoom(v=>Math.max(.65,v-.15))}><Minus/></button><span/><button title="Reset view" aria-label="Reset map view" onClick={()=>{setMapZoom(1);setReset(v=>v+1);}}><RotateCcw size={19}/></button></div>
  <div className="compass"><Compass size={34} strokeWidth={1.2}/><span>N</span></div>
  {active&&!selected&&<aside className="hover-preview" onMouseEnter={()=>changeHover(active.id)} onMouseLeave={()=>changeHover(null)}><div className="preview-top"><span>INSIDE THIS HOME</span><span>{active.id}</span></div><button className="preview-image" onClick={()=>open(active)} aria-label={'View '+active.name}><img src={active.images[0]} alt={'Floor plan of '+active.name}/><span><Maximize2 size={16}/></span></button><div className="preview-details"><small>{active.area}</small><h2>{active.name}</h2><p>{stats(active)}</p><span className="home-format">{active.id==='13'?"Walkable 3D home":"Floor-plan decorating"}</span><button onClick={()=>choose(active)}>{"Explore this home"} <ArrowUpRight size={17}/></button></div></aside>}
  {list&&<aside className="home-list"><div className="list-head"><h2>The neighborhood collection</h2><button className="icon" aria-label="Close home list" onClick={()=>setList(false)}><X size={18}/></button></div>{visible.map(h=><button key={h.id} className="list-home" onMouseEnter={()=>changeHover(h.id)} onMouseLeave={()=>changeHover(null)} onFocus={()=>setHover(h.id)} onBlur={()=>setHover(null)} onClick={()=>choose(h)}><img src={h.images[0]} alt=""/><span><small>{h.area}</small><strong>{h.name}</strong><em>{stats(h)}</em>{h.decoratorPath&&<span className="home-format">{h.id==='13'?'Walkable 3D home':'Floor-plan decorating'}</span>}</span><ArrowUpRight size={17}/></button>)}</aside>}
  <footer className="map-footer"><span><span className="status-dot"/> San Francisco collection</span><span>Illustrated map · Approximate locations</span><span className="footer-coordinates">37.7749° N &nbsp; 122.4194° W</span></footer>
  {selected&&<div className="modal-backdrop" onClick={close}><section className="viewer" role="dialog" aria-modal="true" aria-labelledby="viewer-title" onClick={e=>e.stopPropagation()}><header className="viewer-header"><div><small>{selected.area} / SAN FRANCISCO</small><h2 id="viewer-title">{selected.name}</h2></div><button ref={closeRef} className="icon" onClick={close} aria-label="Close floor plan"><X/></button></header><div className="viewer-body"><div className="plan-stage"><div className="plan-scroll"><img style={{width:zoom===1?'100%':`${zoom*100}%`,maxWidth:zoom===1?'100%':'none',height:zoom===1?'100%':'auto'}} src={selected.images[page]} alt={'Floor plan '+(page+1)+' of '+selected.name}/></div><div className="plan-tools"><button className="icon" aria-label="Zoom floor plan out" onClick={()=>setZoom(v=>Math.max(1,v-.25))} disabled={zoom===1}><Minus size={18}/></button><span>{Math.round(zoom*100)}%</span><button className="icon" aria-label="Zoom floor plan in" onClick={()=>setZoom(v=>Math.min(3,v+.25))} disabled={zoom===3}><Plus size={18}/></button><div/><button className="icon" aria-label="Fit floor plan" title="Fit floor plan" onClick={()=>setZoom(1)}><Maximize2 size={18}/></button></div></div><aside className="home-info"><span className="collection-tag">THE SAN FRANCISCO COLLECTION</span><h3>A closer look.</h3><div className="fact"><BedDouble/><span>{selected.beds===0?'Studio':selected.beds+' bedrooms'}</span></div><div className="fact"><Bath/><span>{selected.baths} bathrooms</span></div><div className="fact"><Maximize2/><span>{selected.sqft?selected.sqft.toLocaleString()+' sq ft':'Area not listed'}</span></div><div className="info-rule"/>{selected.images.length>1&&<><h4>Floor plans</h4><div className="page-picker">{selected.images.map((src,i)=><button key={src} aria-label={'Show floor plan '+(i+1)} aria-pressed={page===i} onClick={()=>{setPage(i);setZoom(1);}}><img src={src} alt=""/><span>{i+1}</span></button>)}</div></>}{selected.decoratorPath&&<a className="decorate-home" href={selected.decoratorPath+'&plan='+page}><House size={17}/>Decorate this home <ArrowUpRight size={16}/></a>}<p className="source-note">{selected.note||'Approximate dimensions from the original property listing. Current availability may differ.'}</p><a className="download-plan" href={selected.images[page]} download><ArrowDownToLine size={18}/> Download floor plan</a><a className="source-link" href={selected.source} target="_blank" rel="noreferrer">Original listing <ArrowUpRight size={16}/></a></aside></div><footer className="viewer-footer"><button onClick={()=>open(homes[(homes.indexOf(selected)+homes.length-1)%homes.length])}><ArrowLeft size={16}/> Previous home</button><span>{selected.id} / {homes.length}</span><button onClick={()=>open(homes[(homes.indexOf(selected)+1)%homes.length])}>Next home <ArrowRight size={16}/></button></footer></section></div>}
 </main>;
}
