import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";
import { authTables } from "@convex-dev/auth/server";

export default defineSchema({
  ...authTables,
  profiles: defineTable({
    userId: v.id("users"),
    plan: v.union(v.literal("studio"), v.literal("residence"), v.literal("atelier"), v.literal("estate")),
    interval: v.optional(v.union(v.literal("month"), v.literal("year"))),
    credits: v.number(),
    stripeCustomerId: v.optional(v.string()),
    stripeSubscriptionId: v.optional(v.string()),
    subscriptionStatus: v.optional(v.string()),
  }).index("by_user", ["userId"]).index("by_customer", ["stripeCustomerId"]),
  homes: defineTable({
    userId: v.id("users"),
    name: v.string(),
    place: v.optional(v.string()),
    notes: v.optional(v.string()),
    sampleId: v.optional(v.string()),
    style: v.optional(v.string()),
    createdAt: v.number(),
  }).index("by_user", ["userId"]),
  homeFiles: defineTable({
    homeId: v.id("homes"),
    userId: v.id("users"),
    kind: v.union(v.literal("floor_plan"), v.literal("photo")),
    storageId: v.optional(v.id("_storage")),
    assetKey: v.optional(v.string()),
    fileName: v.string(),
    contentType: v.string(),
    size: v.number(),
    createdAt: v.number(),
  }).index("by_home", ["homeId"]),
  customFurniture: defineTable({
    userId: v.id("users"),
    name: v.string(),
    category: v.string(),
    widthM: v.number(),
    depthM: v.number(),
    heightM: v.number(),
    glbStorageId: v.optional(v.id("_storage")),
    previewStorageId: v.optional(v.id("_storage")),
    glbKey: v.optional(v.string()),
    previewKey: v.optional(v.string()),
    creditsCharged: v.number(),
    createdAt: v.number(),
  }).index("by_user", ["userId"]),
  catalogItems: defineTable({
    slug: v.string(),
    ownerId: v.optional(v.id("users")),
    name: v.string(),
    category: v.string(),
    description: v.string(),
    materials: v.array(v.string()),
    widthM: v.number(),
    depthM: v.number(),
    heightM: v.number(),
    provenance: v.string(),
    dimensionsNote: v.optional(v.string()),
    retailer: v.string(),
    sourceUrl: v.string(),
    photoUrl: v.string(),
    articleNumber: v.string(),
    checkedDate: v.string(),
    glbKey: v.string(),
    previewKey: v.string(),
    blendKey: v.optional(v.string()),
    viewerOrbit: v.optional(v.string()),
    published: v.boolean(),
    createdAt: v.number(),
  }).index("by_slug", ["slug"]).index("by_owner", ["ownerId"]).index("by_published", ["published"]),
  interiors: defineTable({
    slug: v.optional(v.string()),
    homeId: v.optional(v.id("homes")),
    userId: v.optional(v.id("users")),
    status: v.union(v.literal("ready"), v.literal("failed")),
    error: v.optional(v.string()),
    title: v.string(),
    subtitle: v.string(),
    beds: v.number(),
    sqft: v.number(),
    planJson: v.string(),
    listingJson: v.string(),
    floorPlanKey: v.optional(v.string()),
    downloadKey: v.optional(v.string()),
    layoutDownloadsJson: v.optional(v.string()),
    location: v.optional(v.string()),
    panoramaKey: v.optional(v.string()),
    updatedAt: v.number(),
  }).index("by_slug", ["slug"]).index("by_home", ["homeId"]),
  generationJobs: defineTable({
    userId: v.id("users"),
    homeId: v.optional(v.id("homes")),
    idempotencyKey: v.string(),
    name: v.string(),
    notes: v.optional(v.string()),
    status: v.union(v.literal("queued"), v.literal("running"), v.literal("validating"), v.literal("completed"), v.literal("failed")),
    error: v.optional(v.string()),
    assetCount: v.optional(v.number()),
    inputKeys: v.array(v.string()),
    interiorStatus: v.optional(v.union(v.literal("ready"), v.literal("failed"))),
    createdAt: v.number(),
    updatedAt: v.number(),
    leaseUntil: v.optional(v.number()),
  }).index("by_user", ["userId"]).index("by_status", ["status"]).index("by_idempotency", ["idempotencyKey"]),
  arrangements: defineTable({
    userId: v.id("users"),
    homeId: v.id("homes"),
    style: v.string(),
    prompt: v.optional(v.string()),
    creditsCharged: v.number(),
    status: v.union(
      v.literal("reserved"),
      v.literal("running"),
      v.literal("completed"),
      v.literal("failed"),
      v.literal("refunded"),
    ),
    summary: v.optional(v.string()),
    pieces: v.optional(v.array(v.object({
      id: v.string(),
      quantity: v.number(),
      reason: v.string(),
    }))),
    openaiResponseId: v.optional(v.string()),
    selection: v.optional(v.array(v.object({ id: v.string(), quantity: v.number() }))),
    placements: v.optional(v.array(v.object({
      id: v.string(),
      instanceId: v.string(),
      x: v.number(),
      z: v.number(),
      r: v.number(),
    }))),
    unplaced: v.optional(v.array(v.object({ instanceId: v.string(), reason: v.string() }))),
    layoutStatus: v.optional(v.string()),
    attempt: v.optional(v.number()),
    issues: v.optional(v.array(v.string())),
    createdAt: v.number(),
  }).index("by_home", ["homeId"]).index("by_user", ["userId"]),
  creditLedger: defineTable({
    userId: v.id("users"),
    delta: v.number(),
    reason: v.string(),
    ref: v.optional(v.string()),
    createdAt: v.number(),
  }).index("by_user", ["userId"]).index("by_ref", ["ref"]),
  stripeEvents: defineTable({
    eventId: v.string(),
    createdAt: v.number(),
  }).index("by_event", ["eventId"]),
});
